# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logdump < Formula
  desc "Real-time log aggregation tool with TUI and MCP server for AI agents"
  homepage "https://github.com/appgram/logdump"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_darwin_amd64.tar.gz"
      sha256 "80523f1e2889df12f002c05b041dcf3f40ffdad48f1af796fb1c4e3a14b9f1cb"

      def install
        bin.install "logdump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_darwin_arm64.tar.gz"
      sha256 "fbb4b0ede7533838a1d9468b0f3bfee07a61c6c0c5f5d95357d0f7572759f6bf"

      def install
        bin.install "logdump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_linux_amd64.tar.gz"
      sha256 "405afa06cdd11face08e54cfeb89e5e08b9fb2bc0df7b137923cf2b31bd707de"
      def install
        bin.install "logdump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_linux_arm64.tar.gz"
      sha256 "e1ab3751bb7d6317309fe768c1b541827009c2672346759a11a83a873d719bfa"
      def install
        bin.install "logdump"
      end
    end
  end

  test do
    system "#{bin}/logdump", "-version"
  end
end
