# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logdump < Formula
  desc "Real-time log aggregation tool with TUI and MCP server for AI agents"
  homepage "https://github.com/appgram/logdump"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_darwin_amd64.tar.gz"
      sha256 "67411b87f4d18e48cd9684848740469431bdb6b4010993b3ea48b1bbe6d96041"

      def install
        bin.install "logdump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_darwin_arm64.tar.gz"
      sha256 "2341e8c6b1f96e9419fdb694555a5def052a92163452b396c941164fcc9328b2"

      def install
        bin.install "logdump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_linux_amd64.tar.gz"
      sha256 "b884ba31606b3dcecd3399fd284628f65b9591869e2bfb23fecd2cd1269e7739"
      def install
        bin.install "logdump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/logdump/releases/download/v1.0.0/logdump_1.0.0_linux_arm64.tar.gz"
      sha256 "2a602537dbb85794e6f0c8f48bacfcb4f258857e8fdc51ce4d06eeed33d1276d"
      def install
        bin.install "logdump"
      end
    end
  end

  test do
    system "#{bin}/logdump", "-version"
  end
end
