# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logdump < Formula
  desc "Real-time log aggregation tool with TUI and MCP server for AI agents"
  homepage "https://github.com/appgram/logdump"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/appgram/logdump/releases/download/v1.0.1/logdump_1.0.1_darwin_amd64.tar.gz"
      sha256 "9cae9ebfd45636070950de4bd9e0a88c21b778dd2c89cc7dd716fe7a76cbad41"

      def install
        bin.install "logdump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/appgram/logdump/releases/download/v1.0.1/logdump_1.0.1_darwin_arm64.tar.gz"
      sha256 "5bfee425c22c1e8f0cf7c2d36c727f1e4de2335a0480ba46a2dff01ba0d92231"

      def install
        bin.install "logdump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/logdump/releases/download/v1.0.1/logdump_1.0.1_linux_amd64.tar.gz"
      sha256 "1f6c6b481f5d3997d2c5f4684c0423c3177c1b02a023f3e3347ad61ab7f7859f"
      def install
        bin.install "logdump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/logdump/releases/download/v1.0.1/logdump_1.0.1_linux_arm64.tar.gz"
      sha256 "dadf025d6f0ea2ba912c749c3e4ed482bce1f63f552c51497745f57a58c7b82c"
      def install
        bin.install "logdump"
      end
    end
  end

  test do
    system "#{bin}/logdump", "-version"
  end
end
