# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Td < Formula
  desc "Minimal todo app with beautiful TUI, inline task syntax, and smart dashboard"
  homepage "https://github.com/appgram/td"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/appgram/td/releases/download/v1.0.0/td_1.0.0_darwin_amd64.tar.gz"
      sha256 "b753ffdd32b17df5d3e5b2ebd6853080b21fd28d7940771f060f76ecf86018c7"

      def install
        bin.install "td"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/appgram/td/releases/download/v1.0.0/td_1.0.0_darwin_arm64.tar.gz"
      sha256 "1981b2fb6b67bd56b57322e516fd2d6d0c88e567b2d44c61352f1c218d9f617c"

      def install
        bin.install "td"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/td/releases/download/v1.0.0/td_1.0.0_linux_amd64.tar.gz"
      sha256 "8d71fc2351500e6de2245a0e05270216cb3eb673c2fdda1ec37203a2bb361f26"
      def install
        bin.install "td"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgram/td/releases/download/v1.0.0/td_1.0.0_linux_arm64.tar.gz"
      sha256 "2f2caa57c6b91e2e9396bf990d6db2718b6e8b5013669943f398fe54d68e4762"
      def install
        bin.install "td"
      end
    end
  end

  test do
    system "#{bin}/td", "-version"
  end
end
